global:
  environment: Production
  aws: 
    region: us-east-1 #can be changed based on requirement
  dbSecretName: prod-db-credentials
  imagetag: prod
  db:
    host: prod-db.cluster-xxxx.us-east-1.rds.amazonaws.com #Prod
    user: admin
    password: prodpassword 
    name: bankingapp-Production

accounts:
  image:
    tag: v1.0.0-Prod
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

cards:
  image:
    tag: v1.0.0-Prod 
  replicaCount: 1

loans:
  image:
    tag: v1.0.0-Prod
  replicaCount: 1

gatewayserver:
  image:
    tag: v1.0.0-Prod
  service:
    type: LoadBalancer