global:
  environment: prod
  aws:
    region: us-east-1
  springProfile: prod
  javaToolOptions: ""
  otelExporterEndpoint: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
  otelMetricsExporter: otlp
  otelLogsExporter: none
  
  
  eso:
    enabled: true
    namespace: default
    secretStoreName: aws-secret-store
    service: SecretsManager
    installCRDs: true
  
configMapName: bankingapp-config

# Per-service overrides
accounts:
  serviceAccount:
    name: accounts-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/prod-accounts-rds-access-role
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: prod-db-credentials
  
  monitoring:
    otel:
      enabled: true

cards:
  serviceAccount:
    name: cards-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/prod-cards-rds-access-role
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: prod-db-credentials
  
  monitoring:
    otel:
      enabled: true

loans:
  serviceAccount:
    name: loans-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/prod-loans-rds-access-role
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: prod-db-credentials
  
  monitoring:
    otel:
      enabled: true

gateway:
  serviceAccount:
    create: true
    name: gateway-sa
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: prod-db-credentials
  service:
    type: LoadBalancer
  
  monitoring:
    otel:
      enabled: true