{{ include "common.serviceaccount" . }}

---

{{ include "common.service" . }}

---

{{ include "common.deployment" . }}

---

{{ include "common.networkpolicy" . }}

---

{{ include "common.denyAllIngress" . }}

---

{{ include "common.denyAllEgress" . }}

---

{{- include "common.servicemonitor" . }}

---

{{ include "common.poddisruptionbudget" . }}