{{ include "common.serviceaccount" . }}

---

{{ include "common.service" . }}

---

{{ include "common.deployment" . }}

---

{{ include "common.denyAllIngress" . }}

---

{{ include "common.denyAllEgress" . }}
