apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.accounts.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
  "helm.sh/hook": post-install,post-upgrade
  "helm.sh/hook-weight": "10"
  "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.global.eso.secretStoreName | default "aws-secret-store" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.accounts.secretName }}       # NOTE: In this demo environment, all microservices share a single RDS instance
    creationPolicy: Owner                         # and a single Secrets Manager secret. This is intentional to minimize cloud cost
  data:                                           # while still demonstrating IRSA + External Secrets end-to-end.
    - secretKey: DB_USER                          # in real production environments, each microservice would typically have its own database
      remoteRef:                                  # and its own Secrets Manager secret.
        key: {{ .Values.accounts.secretName }}     
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.accounts.secretName }}
        property: password
    - secretKey: HOST
      remoteRef:
        key: {{ .Values.accounts.secretName }}
        property: dbhost
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.accounts.secretName }}
        property: dbname
