apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.global.eso.secretStoreName }}
  namespace: {{ .Values.global.eso.namespace }}
spec:
  provider:
    aws:
      service: {{ .Values.global.eso.service }}
      region: {{ .Values.global.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: accounts-sa
            namespace: {{ .Values.global.eso.namespace | default "default" }}