apiVersion: v2
name: dev-env
description: Development environment for Banking App
type: application
version: 0.1.0

dependencies:
  - name: accounts
    version: 0.1.0
    repository: "file://../../bankingapp-services/accounts"
  - name: cards
    version: 0.1.0
    repository: "file://../../bankingapp-services/cards"
  - name: loans
    version: 0.1.0
    repository: "file://../../bankingapp-services/loans"
  - name: gatewayserver
    version: 0.1.0
    repository: "file://../../bankingapp-services/gatewayserver"

