global:
  environment: dev
  aws: 
    region: us-east-1
  dbSecretName: dev-db-credentials
  imagetag: dev
  db:
    host: dev-db.cluster-xxxx.us-east-1.rds.amazonaws.com
    user: admin
    password: devpassword
    name: bankingapp

accounts:
  image:
    tag: v1.0.0-dev
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

cards:
  image:
    tag: v1.0.0-dev
  replicaCount: 1

loans:
  image:
    tag: v1.0.0-dev
  replicaCount: 1

gatewayserver:
  image:
    tag: v1.0.0-dev
  service:
    type: LoadBalancer