global:
  environment: dev
  aws:
    region: us-east-1
  springProfile: dev
  javaToolOptions: ""
  otelExporterEndpoint: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
  otelMetricsExporter: otlp
  otelLogsExporter: none
  
  eso:
    enabled: true
    namespace: default
    secretStoreName: aws-secret-store
    service: SecretsManager
    installCRDs: true
  
configMapName: bankingapp-config

# Per-service overrides
accounts:
  serviceAccount:
    create: true
    name: accounts-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-accounts-rds-access-role

  replicaCount: 1
  secretName: dev-db-credentials
  
  monitoring:
    enabled: true
    otel:
      enabled: true

cards:
  serviceAccount:
    create: true
    name: cards-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-cards-rds-access-role

  replicaCount: 1
  secretName: dev-db-credentials
  
  monitoring:
    enabled: true
    otel:
      enabled: true

loans:
  serviceAccount:
    create: true
    name: loans-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-loans-rds-access-role

  replicaCount: 1
  secretName: dev-db-credentials
  
  monitoring:
    enabled: true
    otel:
      enabled: true

gateway:
  serviceAccount:
    create: true
    name: gateway-sa

  replicaCount: 1
  secretName: dev-db-credentials
  service:
    type: ClusterIP
  
  monitoring:
    enabled: true
    otel:
      enabled: true