{{ include "common.deployment" . }}

---

{{ include "common.service" . }}

---

{{ include "common.serviceaccount" . }}

---

{{ include "common.networkpolicy" . }}

---

{{ include "common.hpa" . }}
