apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.dbSecretName | default "dev-db-credentials" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.global.db.host | quote }}
  DB_USER: {{ .Values.global.db.user | quote }}
  DB_PASSWORD: {{ .Values.global.db.password | quote }}
  DB_NAME: {{ .Values.global.db.name | quote }}
  AWS_REGION: {{ .Values.global.aws.Region | quote }}