# Default values for bankingapp-services/accounts.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

serviceAccount:
  name: accounts-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/dev-rds-access-role

replicaCount: 2

global:
  configMapName: bankingapp-config
  springProfile: default
  db:                                     # ADD: move DB fields under global.db
    host: your-db-host
    user: your-db-user
    password: your-db-password
    name: your-db-name
  aws:
    region: us-east-1

image:
  repository: 063630846340.dkr.ecr.us-east-1.amazonaws.com/bankingapp-accounts
  tag: v1.0.0

containerPort: 8080
servicePort: 8080

service:
  type: ClusterIP
  Port: 8080
  targetPort: 8080

otel_enabled: true
config_enabled: true
discovery_enabled: true

dbSecretName: dev-db-credentials

db:
  secretName: dev-db-credentials
  useAwsSecretsManager: true
  hostKey: DB_HOST
  userKey: DB_USER
  passwordKey: DB_PASSWORD

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi