name: CI - Gateway Service

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["test-workflows"]
    paths:
      - "gatewayserver/**"
  pull_request:
    paths:
      - "gatewayserver/**"

permissions:
  contents: read
  id-token: write

env:
  SERVICE: gateway
  SERVICE_DIR: ./gatewayserver
  AWS_REGION: us-east-1
  REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:

  # -------------------------------
  # LINT & UNIT TESTS
  # -------------------------------
  Lint-And-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: lint + test + coverage
        run: ./.github/scripts/01-test-java.sh gatewayserver

      - name: Upload Test & Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage
          path: |
            gatewayserver/target/site/jacoco
            gatewayserver/target/surefire-reports


  # -------------------------------
  # Trivy File System Scan
  # -------------------------------
  Trivy-FS-Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Trivy Cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/trivy
          key: trivy-db-${{ runner.os }} 

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Trivy Scan + report
        run: ./.github/scripts/02-trivy-fs-scan.sh gatewayserver

      - name: Upload Trivy FS Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: gateway-trivy-FS-report.txt



  # -------------------------------
  # BUILD & PUSH DOCKER IMAGE
  # -------------------------------
  Build-And-Push:
    runs-on: ubuntu-latest
    needs: [Lint-And-Test, Trivy-FS-Scan]

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS + ECR
        uses: ./.github/actions/env-setup
        with:
          aws_role: arn:aws:iam::063630846340:role/oidc-github
          aws_region: ${{ env.AWS_REGION }}
          registry: ${{ env.REGISTRY }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Buildx & Cache
        run: ./.github/scripts/03-setup-buildx-cache.sh

      - name: Setup AWS + ECR
        uses: ./.github/actions/env-setup
        with:
          aws_role: arn:aws:iam::063630846340:role/oidc-github
          aws_region: ${{ env.AWS_REGION }}
          registry: ${{ env.REGISTRY }}

      - name: Build & Push Docker Image
        run: ./.github/scripts/04-build-push-image.sh gateway ./gatewayserver ${{ env.REGISTRY }} ${{ env.AWS_REGION }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Update Docker Cache
        run: ./.github/scripts/docker-cache-cleanup.sh

      - name: Save Build Metadata
        run: echo "Image built at $(date)" > build-info.txt

      - name: Upload Build Info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info.txt

  # -------------------------------
  # SECURE IMAGE & SIGNING
  # -------------------------------
  Scan-And-SBOM:
    runs-on: ubuntu-latest
    needs: [Lint-And-Test, Build-And-Push]
    steps:
    - uses: actions/checkout@v3
    - name: Setup AWS + ECR
      uses: ./.github/actions/env-setup
      with:
        aws_role: arn:aws:iam::063630846340:role/oidc-github
        aws_region: ${{ env.AWS_REGION }}
        registry: ${{ env.REGISTRY }}
    - name: Trivy Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: trivy-db-${{ runner.os }}
    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.0    
    - name: Trivy Image Scan
      run: ./.github/scripts/05-trivy-image-scan.sh ${{ env.SERVICE }} ${{ env.REGISTRY }} ${{ env.AWS_REGION }}
    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: gateway-trivy-report
        path: gateway-trivy-image-report.txt
    - name: Generate SBOM (CycloneDX)
      run: |
        trivy image --format cyclonedx \
          --output gateway-sbom.xml \
          ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: SBOM Artifacts
        path: ${{ env.SERVICE }}-sbom.xml

  # -------------------------------
  # Cosign Signature and Verify it
  # -------------------------------
  Sign-And-Verify:
    runs-on: ubuntu-latest
    needs: Build-And-Push
    steps:
    - uses: actions/checkout@v3
    - name: Setup AWS + ECR
      uses: ./.github/actions/env-setup
      with:
        aws_role: arn:aws:iam::063630846340:role/oidc-github
        aws_region: ${{ env.AWS_REGION }}
        registry: ${{ env.REGISTRY }}
    - name: Install Cosign
      run: |
        wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
        sudo mv cosign-linux-amd64 /usr/local/bin/cosign
        sudo chmod +x /usr/local/bin/cosign
    - name: Sign Docker Image (keyless OIDC)
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest
        cosign verify \
          --certificate-identity "https://github.com/YonatanDas/Multi-Environment-Microservices/.github/workflows/gateway.yaml@refs/heads/test-workflows" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest

    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        path: gateway-sbom.xml


  Collect-Artifacts:
    runs-on: ubuntu-latest
    needs: [Lint-And-Test, Trivy-FS-Scan, Build-And-Push, Scan-And-SBOM, Sign-And-Verify]

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS + ECR
        uses: ./.github/actions/env-setup
        with:
          aws_role: arn:aws:iam::063630846340:role/oidc-github
          aws_region: ${{ env.AWS_REGION }}
          registry: ${{ env.REGISTRY }}
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected-artifacts/

      - name: Upload to S3 (optional)
        run: aws s3 sync collected-artifacts/ s3://my-ci-artifacts55/${{ github.sha }}/


        