name: CI - Gateway Service

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["test-workflows"]
    paths:
      - "gatewayserver/**"
  pull_request:
    paths:
      - "gatewayserver/**"

permissions:
  contents: read
  id-token: write

env:
  SERVICE: gateway
  AWS_REGION: us-east-1
  REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:

  # -------------------------------
  # LINT & UNIT TESTS
  # -------------------------------
  Lint-And-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make scripts executable
        run: chmod +x .github/workflows/reusable/*.sh

      - name: lint + test + coverage
        run: ./.github/workflows/reusable/test-java.sh gatewayserver

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Trivy Scan + report
        run: ./.github/workflows/reusable/trivy-fs-scan.sh gatewayserver



  # -------------------------------
  # BUILD & PUSH DOCKER IMAGE
  # -------------------------------
  Build-And-Push:
    runs-on: ubuntu-latest
    needs: Lint-And-Test

    steps:
      - uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x .github/workflows/reusable/*.sh

      - name: Restore Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: Linux-buildx-${{ github.sha }}
          restore-keys: |
            buildx-${{ env.SERVICE }}-
            buildx-

      - name: Setup Buildx & Cache
        run: ./.github/workflows/reusable/setup-buildx-cache.sh

      - name: Configure AWS OIDC Access
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::063630846340:role/oidc-github
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: AWS ECR Login
        run: ./.github/workflows/reusable/aws-oidc-login.sh ${{ env.AWS_REGION }} ${{ env.REGISTRY }}

      - name: Build & Push Docker Image
        run: ./.github/workflows/reusable/build-push-image.sh gateway ./gatewayserver ${{ env.REGISTRY }} ${{ env.AWS_REGION }}

      - name: Update Docker Cache
        run: ./.github/workflows/reusable/docker-cache-cleanup.sh

  # -------------------------------
  # SECURE IMAGE & SIGNING
  # -------------------------------
  Scan-And-Sign:
    runs-on: ubuntu-latest
    needs: Build-And-Push

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup AWS + ECR
      uses: ./.github/actions/env-setup
      with:
        aws_role: arn:aws:iam::063630846340:role/oidc-github
        aws_region: ${{ env.AWS_REGION }}
        registry: ${{ env.REGISTRY }}

    - name: Restore Trivy DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: trivy-db-${{ runner.os }}
        restore-keys: |
          trivy-db-${{ runner.os }}-      

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.0  

    - name: Trivy Image Scan
      run: ./.github/workflows/reusable/trivy-image-scan.sh gateway ${{ env.REGISTRY }} ${{ env.AWS_REGION }}

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: gateway-trivy-report
        path: gateway-trivy-image-report.txt
    
    - name: Generate SBOM (CycloneDX)
      run: |
        trivy image --format cyclonedx \
          --output gateway-sbom.xml \
          ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest

    - name: Install Cosign
      run: |
        wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
        sudo mv cosign-linux-amd64 /usr/local/bin/cosign
        sudo chmod +x /usr/local/bin/cosign

    - name: Sign Docker Image (keyless OIDC)
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest