name: CI - Gateway Service

on:
  push:
    branches: ["test-workflows"]
    paths:
      - "gatewayserver/**"
  pull_request:
    paths:
      - "gatewayserver/**"

permissions:
  contents: read
  id-token: write

env:
  SERVICE: gateway
  AWS_REGION: us-east-1
  REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:

  # -------------------------------
  # LINT & UNIT TESTS
  # -------------------------------
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('gatewayserver/pom.xml') }}
          restore-keys: maven-

      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make scripts executable
        run: chmod +x .github/workflows/reusable/*.sh

      - name: lint + test + coverage
        run: ./.github/workflows/reusable/test-java.sh gatewayserver

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Trivy Scan + report
        run: ./.github/workflows/reusable/trivy-fs-scan.sh gatewayserver



  # -------------------------------
  # BUILD & PUSH DOCKER IMAGE
  # -------------------------------
  build-push:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Configure AWS OIDC Access
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::063630846340:role/oidc-github
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./gatewayserver
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ steps.vars.outputs.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest
          cache-from: src=/tmp/.buildx-cache
          cache-to: dest=/tmp/.buildx-cache-new,mode=max

      - name: Update Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache



  # -------------------------------
  # IMAGE SECURITY SCAN
  # -------------------------------
  image-scan:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Image Scan
        run: |
          trivy image \
            --exit-code 0 \
            --severity HIGH,CRITICAL \
            ${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ github.sha }}
