name: CI for Microservices 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "test-workflows" ]
    paths:
      - "accounts/**"
      - "cards/**"
      - "loans/**"
      - "gatewayserver/**"
  pull_request:
    paths:
      - "accounts/**"
      - "cards/**"
      - "loans/**"
      - "gatewayserver/**"

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  
  services-changed:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: detect
        with:
          filters: |
            accounts: 'accounts/**'
            cards: 'cards/**'
            loans: 'loans/**'
            gatewayserver: 'gatewayserver/**'
        
  # -------------------------------
  # LINT & UNIT TESTS
  # -------------------------------
  Lint-And-Test:
    runs-on: ubuntu-latest
    needs: services-changed 
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.services) }}
    env:
          SERVICE: ${{ matrix.SERVICE }}
          SERVICE_DIR: ./${{ matrix.SERVICE }}    

    steps:
      - uses: actions/checkout@v3
  
      - name: Restore Docker cache
        uses: ./.github/actions/caching
        with:
          cache-key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: lint + test + coverage
        run: ./.github/scripts/01-test-java.sh ${{ env.SERVICE }}

      - name: Upload Test & Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE }}-test-and-coverage
          path: |
            ${{ env.SERVICE_DIR }}/target/site/jacoco
            ${{ env.SERVICE_DIR }}/target/surefire-reports


  # -------------------------------
  # Trivy File System Scan
  # -------------------------------
  Trivy-FS-Scan:
    runs-on: ubuntu-latest
    needs: [services-changed] 
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.services) }}
    env:
      SERVICE: ${{ matrix.SERVICE }}
      SERVICE_DIR: ./${{ matrix.SERVICE }}

    steps:
      - uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Trivy Cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/trivy
          key: trivy-db-${{ runner.os }} 

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Trivy Scan + report
        run: ./.github/scripts/02-trivy-fs-scan.sh ${{ env.SERVICE }}

      - name: Upload Trivy FS Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE }}-trivy-fs-report
          path: ${{ env.SERVICE }}-trivy-FS-report.txt



  # -------------------------------
  # BUILD & PUSH DOCKER IMAGE
  # -------------------------------
  Build-And-Push:
    runs-on: ubuntu-latest
    needs: [Lint-And-Test, Trivy-FS-Scan, services-changed ]
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.services) }}
    env:
      SERVICE: ${{ matrix.SERVICE }}
      SERVICE_DIR: ./${{ matrix.SERVICE }}
      AWS_REGION: us-east-1
      REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com 

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS + ECR
        uses: ./.github/actions/env-setup
        with:
          aws_role: arn:aws:iam::063630846340:role/oidc-github
          aws_region: ${{ env.AWS_REGION }}
          registry: ${{ env.REGISTRY }}

      - name: Restore Docker cache
        uses: ./.github/actions/caching
        with:
          cache-key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Setup Buildx & Cache
        run: ./.github/scripts/03-setup-buildx-cache.sh

      - name: Setup AWS + ECR
        uses: ./.github/actions/env-setup
        with:
          aws_role: arn:aws:iam::063630846340:role/oidc-github
          aws_region: ${{ env.AWS_REGION }}
          registry: ${{ env.REGISTRY }}

      - name: Build Image
        run: |
          ./.github/scripts/04a-build-image.sh \
            "${{ env.SERVICE }}" \
            "${{ env.SERVICE_DIR }}" \
            "${{ env.REGISTRY }}" \
            "${{ env.AWS_REGION }}"

      - name: Scan JAR before Push
        run: ./.github/scripts/04b-scan-jar-pre-push.sh "${{ env.SERVICE }}"

      - name: Push Image to ECR
        run: ./.github/scripts/04c-push-image.sh \
            "${{ env.SERVICE }}" \
            "${{ env.REGISTRY }}" \
            "${{ env.AWS_REGION }}"

      - name: Update Docker Cache
        run: ./.github/scripts/docker-cache-cleanup.sh

      - name: Save Build Metadata
        run: echo "Image built at $(date)" > build-info.txt
      - name: Upload Build Info
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE }}-build-info
          path: build-info.txt

  # -------------------------------
  # SECURE IMAGE & SIGNING
  # ------------------------------- 
  Scan-And-SBOM:
    runs-on: ubuntu-latest
    needs: [Lint-And-Test, Build-And-Push, services-changed ]
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.services) }}
    env:
      SERVICE: ${{ matrix.SERVICE }}
      SERVICE_DIR: ./${{ matrix.SERVICE }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup AWS + ECR
      uses: ./.github/actions/env-setup
      with:
        aws_role: arn:aws:iam::063630846340:role/oidc-github
        aws_region: ${{ env.AWS_REGION }}
        registry: ${{ env.REGISTRY }}
    - name: Trivy Image Scan & SBOM
      run: ./.github/scripts/05-trivy-image-scan.sh \
            "${{ env.SERVICE }}" \
            "${{ env.REGISTRY }}" \
            "${{ env.AWS_REGION }}"

    - name: Upload Trivy Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SERVICE }}-trivy-sbom
        path: .ci_artifacts/${{ env.SERVICE }}/${{ github.sha }}/trivy-scan/


  # -------------------------------
  # Cosign Signature and Verify it
  # -------------------------------
  Sign-And-Verify:
    runs-on: ubuntu-latest
    needs: [Build-And-Push, services-changed]
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.services) }}
    env:
      SERVICE: ${{ matrix.SERVICE }}
      SERVICE_DIR: ./${{ matrix.SERVICE }}    
    steps:
    - uses: actions/checkout@v3
    - name: Setup AWS + ECR
      uses: ./.github/actions/env-setup
      with:
        aws_role: arn:aws:iam::063630846340:role/oidc-github
        aws_region: ${{ env.AWS_REGION }}
        registry: ${{ env.REGISTRY }}
    - name: Cosign Sign and Verify
      run: ./.github/scripts/06-cosign-sign-verify.sh \
            "${{ env.SERVICE }}" \
            "${{ env.REGISTRY }}" \
            ".github/workflows/${{ env.SERVICE }}.yaml" \
            "refs/heads/test-workflows"

  # -------------------------------
  # COLLECT ALL ARTIFACTS AND UPLOAD TO S3
  # -------------------------------
  Collect-Artifacts:
    runs-on: ubuntu-latest
    needs: [Lint-And-Test, Trivy-FS-Scan, Build-And-Push, Scan-And-SBOM, Sign-And-Verify]
    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS + ECR
        uses: ./.github/actions/env-setup
        with:
          aws_role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github
          aws_region: ${{ env.AWS_REGION }}
          registry: ${{ env.REGISTRY }}
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected-artifacts/
      - name: Upload to S3
        run: ./.github/scripts/artifact_collect_and_s3.sh "${{ env.SERVICE }}" "my-ci-artifacts55" "builds"