name: CI - Gateway Service

on:
  push:
    branches: ["test-workflows"]
    paths:
      - "gatewayserver/**"
  pull_request:
    paths:
      - "gatewayserver/**"

env:
  SERVICE: gateway
  AWS_REGION: us-east-1
  REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:

  # -------------------------------
  # LINT & UNIT TESTS
  # -------------------------------
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('gatewayserver/pom.xml') }}
          restore-keys: maven-

      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run Checkstyle (Lint)
        working-directory: ./gatewayserver
        run: mvn -B checkstyle:check

      - name: Run Unit Tests
        working-directory: ./gatewayserver
        run: mvn -B test

      - name: Generate Code Coverage Report
        working-directory: ./gatewayserver
        run: mvn jacoco:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: gatewayserver/target/site/jacoco/

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Trivy FS Security Scan
        run: trivy fs --exit-code 0 --no-progress --severity HIGH,CRITICAL gatewayserver/
        
      - name: Save Trivy Report
        run: trivy fs --exit-code 0 --no-progress --severity HIGH,CRITICAL --format table -o trivy-report.txt gatewayserver/
      - uses: actions/upload-artifact@v4
        with:
          name: gateway-trivy-report
          path: trivy-report.txt



  # -------------------------------
  # BUILD & PUSH DOCKER IMAGE
  # -------------------------------
  build-push:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Configure AWS OIDC Access
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-eks-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./gatewayserver
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ steps.vars.outputs.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.SERVICE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Update Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache



  # -------------------------------
  # IMAGE SECURITY SCAN
  # -------------------------------
  image-scan:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Image Scan
        run: |
          trivy image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            ${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ github.sha }}
